import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import type { Manifest } from "../src/manifest.ts";
import {
  addMarker,
  BACKUP_DIR,
  buildManifest,
  captureBackup,
  detectDrift,
  generatedMarker,
  hasGeneratedMarker,
  hashContent,
  listBackups,
  MANIFEST_FILE,
  ownedPaths,
  preservedPaths,
  readBackup,
  readManifest,
  restoreBackup,
  staleFiles,
  writeBackup,
  writeManifest,
} from "../src/manifest.ts";

// ─── Fixtures ──────────────────────────────────────────────────────────────

let testRoot: string;

beforeEach(() => {
  testRoot = join(tmpdir(), `agentfile-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(testRoot, { recursive: true });
});

afterEach(() => {
  if (existsSync(testRoot)) {
    rmSync(testRoot, { recursive: true, force: true });
  }
});

// ─── hashContent ───────────────────────────────────────────────────────────

describe("hashContent", () => {
  it("returns a 64-char hex SHA-256 digest", () => {
    const hash = hashContent("hello world");
    expect(hash).toHaveLength(64);
    expect(hash).toMatch(/^[0-9a-f]{64}$/);
  });

  it("returns different hashes for different content", () => {
    const a = hashContent("hello");
    const b = hashContent("world");
    expect(a).not.toBe(b);
  });

  it("returns the same hash for identical content", () => {
    expect(hashContent("test")).toBe(hashContent("test"));
  });
});

// ─── generatedMarker ──────────────────────────────────────────────────────

describe("generatedMarker", () => {
  it("returns HTML comment for .md files", () => {
    const marker = generatedMarker("instructions.md");
    expect(marker).toContain("<!-- generated by agentfile");
  });

  it("returns HTML comment for .mdc files", () => {
    const marker = generatedMarker("skill.mdc");
    expect(marker).toContain("<!-- generated by agentfile");
  });

  it("returns null for .json files", () => {
    expect(generatedMarker("config.json")).toBeNull();
  });

  it("returns HTML comment for other extensions", () => {
    const marker = generatedMarker("file.yaml");
    expect(marker).toContain("<!-- generated by agentfile");
  });
});

// ─── hasGeneratedMarker ────────────────────────────────────────────────────

describe("hasGeneratedMarker", () => {
  it("returns true when content starts with the marker", () => {
    const content = "<!-- generated by agentfile — do not edit directly -->\n# Title";
    expect(hasGeneratedMarker(content)).toBe(true);
  });

  it("returns true even with leading whitespace", () => {
    const content = "  \n<!-- generated by agentfile — do not edit directly -->\n# Title";
    expect(hasGeneratedMarker(content)).toBe(true);
  });

  it("returns false for content without marker", () => {
    expect(hasGeneratedMarker("# Regular file")).toBe(false);
  });
});

// ─── addMarker ─────────────────────────────────────────────────────────────

describe("addMarker", () => {
  it("prepends marker to markdown content", () => {
    const result = addMarker("file.md", "# Title");
    expect(result).toMatch(/^<!-- generated by agentfile/);
    expect(result).toContain("# Title");
  });

  it("does not double-add marker", () => {
    const once = addMarker("file.md", "# Title");
    const twice = addMarker("file.md", once);
    expect(once).toBe(twice);
  });

  it("returns content unchanged for .json files", () => {
    const json = '{"key": "value"}';
    expect(addMarker("file.json", json)).toBe(json);
  });

  it("inserts the marker after a leading frontmatter block, never above it", () => {
    const rule = '---\nglobs:\n  - "src/**"\nalwaysApply: false\n---\n\nRule body.\n';
    const marked = addMarker("rule.mdc", rule);

    // A comment on line one would stop the frontmatter being frontmatter.
    expect(marked.startsWith("---\n")).toBe(true);
    expect(marked).toContain("---\n<!-- generated by agentfile");
    expect(hasGeneratedMarker(marked)).toBe(true);
    expect(addMarker("rule.mdc", marked)).toBe(marked);
  });

  it("treats --- below the first line as content, not frontmatter", () => {
    const markdown = "# Title\n\n---\n\nsection\n";
    expect(addMarker("file.md", markdown)).toMatch(/^<!-- generated by agentfile/);
  });
});

// ─── readManifest / writeManifest ──────────────────────────────────────────

describe("readManifest / writeManifest", () => {
  it("returns null when no manifest exists", () => {
    expect(readManifest(testRoot)).toBeNull();
  });

  it("round-trips a manifest through write then read", () => {
    const manifest: Manifest = {
      version: 1,
      lastSync: "2025-01-01T00:00:00.000Z",
      files: [
        {
          path: ".github/copilot-instructions.md",
          ownership: "owned",
          source: "copilot",
          hash: hashContent("test content"),
          generatedAt: "2025-01-01T00:00:00.000Z",
        },
      ],
    };

    writeManifest(testRoot, manifest);
    const read = readManifest(testRoot);

    expect(read).toEqual(manifest);
  });

  it("returns null for corrupted JSON", () => {
    writeFileSync(join(testRoot, MANIFEST_FILE), "not json", "utf-8");
    expect(readManifest(testRoot)).toBeNull();
  });
});

// ─── buildManifest ─────────────────────────────────────────────────────────

describe("buildManifest", () => {
  it("creates entries for all owned files", () => {
    const ownedFiles = new Map<string, { content: string; source: string }>();
    ownedFiles.set("a.md", { content: "hello", source: "copilot" });
    ownedFiles.set("b.md", { content: "world", source: "claude" });

    const manifest = buildManifest(ownedFiles, null);

    expect(manifest.version).toBe(1);
    expect(manifest.files).toHaveLength(2);
    expect(manifest.files[0].path).toBe("a.md");
    expect(manifest.files[0].ownership).toBe("owned");
    expect(manifest.files[0].source).toBe("copilot");
    expect(manifest.files[0].hash).toBe(hashContent("hello"));
    expect(manifest.files[1].path).toBe("b.md");
  });

  it("carries forward preserved entries from previous manifest", () => {
    const previous: Manifest = {
      version: 1,
      lastSync: "2025-01-01T00:00:00.000Z",
      files: [
        {
          path: "preserved.md",
          ownership: "preserved",
          source: "manual",
          hash: hashContent("preserved"),
          generatedAt: "2025-01-01T00:00:00.000Z",
        },
      ],
    };

    const ownedFiles = new Map<string, { content: string; source: string }>();
    ownedFiles.set("a.md", { content: "hello", source: "copilot" });

    const manifest = buildManifest(ownedFiles, previous);

    expect(manifest.files).toHaveLength(2);
    const preserved = manifest.files.find((f) => f.path === "preserved.md");
    expect(preserved?.ownership).toBe("preserved");
  });

  it("does not carry forward previously owned entries that are now re-generated", () => {
    const previous: Manifest = {
      version: 1,
      lastSync: "2025-01-01T00:00:00.000Z",
      files: [
        {
          path: "a.md",
          ownership: "owned",
          source: "copilot",
          hash: hashContent("old"),
          generatedAt: "2025-01-01T00:00:00.000Z",
        },
      ],
    };

    const ownedFiles = new Map<string, { content: string; source: string }>();
    ownedFiles.set("a.md", { content: "new", source: "copilot" });

    const manifest = buildManifest(ownedFiles, previous);

    expect(manifest.files).toHaveLength(1);
    expect(manifest.files[0].hash).toBe(hashContent("new"));
  });

  it("sorts entries by path", () => {
    const ownedFiles = new Map<string, { content: string; source: string }>();
    ownedFiles.set("z.md", { content: "z", source: "copilot" });
    ownedFiles.set("a.md", { content: "a", source: "copilot" });

    const manifest = buildManifest(ownedFiles, null);
    expect(manifest.files[0].path).toBe("a.md");
    expect(manifest.files[1].path).toBe("z.md");
  });
});

// ─── ownedPaths / preservedPaths ───────────────────────────────────────────

describe("ownedPaths / preservedPaths", () => {
  const manifest: Manifest = {
    version: 1,
    lastSync: "2025-01-01T00:00:00.000Z",
    files: [
      {
        path: "owned.md",
        ownership: "owned",
        source: "copilot",
        hash: "abc",
        generatedAt: "2025-01-01T00:00:00.000Z",
      },
      {
        path: "preserved.md",
        ownership: "preserved",
        source: "copilot",
        hash: "def",
        generatedAt: "2025-01-01T00:00:00.000Z",
      },
      {
        path: "unmanaged.md",
        ownership: "unmanaged",
        source: "",
        hash: "ghi",
        generatedAt: "2025-01-01T00:00:00.000Z",
      },
    ],
  };

  it("returns only owned paths", () => {
    expect(ownedPaths(manifest)).toEqual(["owned.md"]);
  });

  it("returns only preserved paths", () => {
    expect(preservedPaths(manifest)).toEqual(["preserved.md"]);
  });
});

// ─── detectDrift ───────────────────────────────────────────────────────────

describe("detectDrift", () => {
  it("returns empty when files match", () => {
    const content = "hello world";
    writeFileSync(join(testRoot, "file.md"), content, "utf-8");

    const manifest: Manifest = {
      version: 1,
      lastSync: "2025-01-01T00:00:00.000Z",
      files: [
        {
          path: "file.md",
          ownership: "owned",
          source: "copilot",
          hash: hashContent(content),
          generatedAt: "2025-01-01T00:00:00.000Z",
        },
      ],
    };

    expect(detectDrift(testRoot, manifest)).toEqual([]);
  });

  it("detects modified files", () => {
    writeFileSync(join(testRoot, "file.md"), "modified content", "utf-8");

    const manifest: Manifest = {
      version: 1,
      lastSync: "2025-01-01T00:00:00.000Z",
      files: [
        {
          path: "file.md",
          ownership: "owned",
          source: "copilot",
          hash: hashContent("original content"),
          generatedAt: "2025-01-01T00:00:00.000Z",
        },
      ],
    };

    expect(detectDrift(testRoot, manifest)).toEqual(["file.md"]);
  });

  it("detects missing files", () => {
    const manifest: Manifest = {
      version: 1,
      lastSync: "2025-01-01T00:00:00.000Z",
      files: [
        {
          path: "missing.md",
          ownership: "owned",
          source: "copilot",
          hash: hashContent("content"),
          generatedAt: "2025-01-01T00:00:00.000Z",
        },
      ],
    };

    expect(detectDrift(testRoot, manifest)).toEqual(["missing.md"]);
  });

  it("ignores non-owned files", () => {
    const manifest: Manifest = {
      version: 1,
      lastSync: "2025-01-01T00:00:00.000Z",
      files: [
        {
          path: "preserved.md",
          ownership: "preserved",
          source: "copilot",
          hash: hashContent("doesn't matter"),
          generatedAt: "2025-01-01T00:00:00.000Z",
        },
      ],
    };

    expect(detectDrift(testRoot, manifest)).toEqual([]);
  });
});

// ─── staleFiles ────────────────────────────────────────────────────────────

describe("staleFiles", () => {
  it("returns files that were owned but are no longer generated", () => {
    const previous: Manifest = {
      version: 1,
      lastSync: "2025-01-01T00:00:00.000Z",
      files: [
        {
          path: "a.md",
          ownership: "owned",
          source: "c",
          hash: "a",
          generatedAt: "2025-01-01T00:00:00.000Z",
        },
        {
          path: "b.md",
          ownership: "owned",
          source: "c",
          hash: "b",
          generatedAt: "2025-01-01T00:00:00.000Z",
        },
      ],
    };

    const current: Manifest = {
      version: 1,
      lastSync: "2025-01-01T00:00:00.000Z",
      files: [
        {
          path: "a.md",
          ownership: "owned",
          source: "c",
          hash: "a",
          generatedAt: "2025-01-01T00:00:00.000Z",
        },
      ],
    };

    expect(staleFiles(previous, current)).toEqual(["b.md"]);
  });

  it("returns empty when all files are still present", () => {
    const manifest: Manifest = {
      version: 1,
      lastSync: "2025-01-01T00:00:00.000Z",
      files: [
        {
          path: "a.md",
          ownership: "owned",
          source: "c",
          hash: "a",
          generatedAt: "2025-01-01T00:00:00.000Z",
        },
      ],
    };

    expect(staleFiles(manifest, manifest)).toEqual([]);
  });
});

// ─── Backup / Restore ──────────────────────────────────────────────────────

describe("captureBackup", () => {
  it("captures existing files", () => {
    writeFileSync(join(testRoot, "a.md"), "content-a", "utf-8");
    writeFileSync(join(testRoot, "b.md"), "content-b", "utf-8");

    const entries = captureBackup(testRoot, ["a.md", "b.md"]);
    expect(entries).toHaveLength(2);
    expect(entries[0]).toEqual({ path: "a.md", content: "content-a" });
    expect(entries[1]).toEqual({ path: "b.md", content: "content-b" });
  });

  it("skips files that do not exist", () => {
    writeFileSync(join(testRoot, "a.md"), "content-a", "utf-8");

    const entries = captureBackup(testRoot, ["a.md", "missing.md"]);
    expect(entries).toHaveLength(1);
    expect(entries[0].path).toBe("a.md");
  });
});

describe("writeBackup / readBackup", () => {
  it("round-trips backup entries", () => {
    const entries = [
      { path: "dir/a.md", content: "hello" },
      { path: "b.md", content: "world" },
    ];

    const backupPath = writeBackup(testRoot, entries, "test-tag");
    expect(backupPath).toContain("test-tag");
    expect(existsSync(backupPath)).toBe(true);

    const read = readBackup(testRoot, "test-tag");
    expect(read).toHaveLength(2);

    const sorted = read.sort((a, b) => a.path.localeCompare(b.path));
    expect(sorted[0]).toEqual({ path: "b.md", content: "world" });
    expect(sorted[1]).toEqual({ path: "dir/a.md", content: "hello" });
  });

  it("readBackup returns empty for missing tag", () => {
    expect(readBackup(testRoot, "nonexistent")).toEqual([]);
  });
});

describe("restoreBackup", () => {
  it("restores files to the project root", () => {
    const entries = [
      { path: "restored.md", content: "restored content" },
      { path: "sub/dir/file.md", content: "nested content" },
    ];

    const restored = restoreBackup(testRoot, entries);
    expect(restored).toEqual(["restored.md", "sub/dir/file.md"]);
    expect(readFileSync(join(testRoot, "restored.md"), "utf-8")).toBe("restored content");
    expect(readFileSync(join(testRoot, "sub/dir/file.md"), "utf-8")).toBe("nested content");
  });
});

describe("listBackups", () => {
  it("returns empty when no backups exist", () => {
    expect(listBackups(testRoot)).toEqual([]);
  });

  it("returns backup tags in reverse order", () => {
    mkdirSync(join(testRoot, BACKUP_DIR, "alpha"), { recursive: true });
    mkdirSync(join(testRoot, BACKUP_DIR, "beta"), { recursive: true });
    mkdirSync(join(testRoot, BACKUP_DIR, "gamma"), { recursive: true });

    const tags = listBackups(testRoot);
    expect(tags).toEqual(["gamma", "beta", "alpha"]);
  });
});
