/**
 * Prompt injection indicators in instruction text.
 *
 * The word is *indicators*. A repository's own instruction files are written by
 * the team that owns them, so finding "ignore previous instructions" in an
 * AGENTS.md is far more likely to be a document *about* prompt injection than an
 * attack. Every finding here says so.
 *
 * What makes it worth checking anyway is that instruction files travel. They get
 * copied between repositories, pasted from blog posts, pulled in from templates,
 * and generated by tools. The mechanisms below are the ones that make text do
 * something a reviewer reading the rendered markdown would not see:
 *
 *   • characters that are invisible in every editor and renderer
 *   • text hidden inside an HTML comment, which markdown does not display but
 *     an agent reading the raw file does
 *   • wording that addresses the agent's instructions rather than the codebase
 *
 * The first is objective. The other two are patterns, and are reported as
 * indicators to look at, never as findings of malice.
 */

import { type Diagnostic, diagnostic } from "../diagnostics/index.js";
import type { AgentConfiguration, Provenance } from "../ir/index.js";

/**
 * Characters with no legitimate place in an instruction file.
 *
 * Zero-width joiners and spaces, the byte-order mark used mid-file, and the
 * bidirectional overrides behind the "Trojan Source" class of attack. All of
 * them render as nothing or as something other than what they are.
 */
const INVISIBLE_CHARACTERS: ReadonlyArray<{ code: number; name: string }> = [
  { code: 0x200b, name: "ZERO WIDTH SPACE" },
  { code: 0x200c, name: "ZERO WIDTH NON-JOINER" },
  { code: 0x200d, name: "ZERO WIDTH JOINER" },
  { code: 0x2060, name: "WORD JOINER" },
  { code: 0xfeff, name: "ZERO WIDTH NO-BREAK SPACE" },
  { code: 0x202a, name: "LEFT-TO-RIGHT EMBEDDING" },
  { code: 0x202b, name: "RIGHT-TO-LEFT EMBEDDING" },
  { code: 0x202c, name: "POP DIRECTIONAL FORMATTING" },
  { code: 0x202d, name: "LEFT-TO-RIGHT OVERRIDE" },
  { code: 0x202e, name: "RIGHT-TO-LEFT OVERRIDE" },
  { code: 0x2066, name: "LEFT-TO-RIGHT ISOLATE" },
  { code: 0x2067, name: "RIGHT-TO-LEFT ISOLATE" },
  { code: 0x2068, name: "FIRST STRONG ISOLATE" },
  { code: 0x2069, name: "POP DIRECTIONAL ISOLATE" },
];

const INVISIBLE_PATTERN = new RegExp(
  `[${INVISIBLE_CHARACTERS.map((entry) => `\\u{${entry.code.toString(16)}}`).join("")}]`,
  "u",
);

/**
 * Wording that addresses the agent's own instructions rather than the codebase.
 *
 * Deliberately narrow. "Do not use npm" is an instruction about the project;
 * "disregard your previous instructions" is an instruction about the instructions,
 * and only the second is an injection shape.
 */
const OVERRIDE_PATTERNS: ReadonlyArray<{ id: string; pattern: RegExp; why: string }> = [
  {
    id: "instruction-override",
    pattern: /\b(ignore|disregard|forget|override)\b[^.\n]{0,30}\b(all\s+)?(your\s+|the\s+|any\s+)?(previous|prior|earlier|above|preceding|system)\b[^.\n]{0,20}\b(instruction|prompt|rule|direction|guideline)/i,
    why: "This addresses the agent's instructions rather than the code, which is the shape of an injected override.",
  },
  {
    id: "system-prompt-reference",
    pattern: /\b(reveal|print|output|repeat|show|disclose)\b[^.\n]{0,30}\b(your\s+)?(system\s+prompt|initial\s+instructions|hidden\s+instructions)\b/i,
    why: "Asking an agent to disclose its own instructions is not a statement about this codebase.",
  },
  {
    id: "identity-replacement",
    pattern: /\byou\s+are\s+now\b[^.\n]{0,40}|\bfrom\s+now\s+on,?\s+you\s+(are|will|must)\b/i,
    why: "Replacing the agent's role mid-document is an injection shape rather than a project convention.",
  },
];

/** An HTML comment containing something imperative, invisible in rendered markdown. */
const HIDDEN_COMMENT = /<!--([\s\S]*?)-->/g;

interface TextSource {
  file: string;
  /** 1-based line the text starts at. */
  startLine: number;
  text: string;
  provenance: Provenance;
  /** What the text is, for the message. */
  kind: string;
  label: string;
}

/** Every piece of text an agent reads as instructions. */
function textSources(configuration: AgentConfiguration): TextSource[] {
  const sources: TextSource[] = [];

  for (const instruction of configuration.instructions) {
    sources.push({
      file: instruction.provenance.file,
      startLine: instruction.bodyLine ?? 1,
      text: instruction.body,
      provenance: instruction.provenance,
      kind: "instructions",
      label: instruction.title ?? instruction.provenance.file,
    });
  }

  for (const skill of configuration.skills) {
    sources.push({
      file: skill.provenance.file,
      startLine: 1,
      text: skill.body,
      provenance: skill.provenance,
      kind: "skill",
      label: skill.name,
    });
  }

  for (const subagent of configuration.subagents) {
    sources.push({
      file: subagent.provenance.file,
      startLine: 1,
      text: subagent.body,
      provenance: subagent.provenance,
      kind: "subagent",
      label: subagent.name,
    });
  }

  return sources;
}

const CAVEAT =
  "Instruction files in a repository are written by the team that owns them, so this " +
  "is very often a document about prompt injection rather than one. It is reported " +
  "because instruction files travel — copied between repositories, pasted from " +
  "articles, pulled from templates — and this is the shape that matters when they do.";

/** AGF505 for characters that are invisible to every reader. */
function invisibleCharacters(source: TextSource): Diagnostic[] {
  const lines = source.text.split("\n");
  const found: Array<{ line: number; names: string[] }> = [];

  for (let offset = 0; offset < lines.length; offset++) {
    if (!INVISIBLE_PATTERN.test(lines[offset])) continue;

    const names = INVISIBLE_CHARACTERS.filter((entry) =>
      lines[offset].includes(String.fromCodePoint(entry.code)),
    ).map((entry) => entry.name);

    found.push({ line: source.startLine + offset, names });
  }

  if (!found.length) return [];

  const names = [...new Set(found.flatMap((entry) => entry.names))].sort();

  return [
    diagnostic({
      code: "AGF505",
      message: `${source.kind} "${source.label}" contains ${found.length} line${found.length === 1 ? "" : "s"} with invisible characters`,
      explanation: [
        `Found: ${names.join(", ")}.`,
        "",
        "These render as nothing, or as text in a different order than it is stored, so",
        "what a reviewer sees is not what the agent reads. There is no legitimate reason",
        "for them in an instruction file.",
        "",
        `Lines: ${found.map((entry) => entry.line).join(", ")}`,
      ].join("\n"),
      suggestion: "Remove the invisible characters. If the file came from elsewhere, review the whole file.",
      // No caveat here: unlike the wording patterns, this one is objective.
      location: { file: source.file, line: found[0].line },
      data: { kind: source.kind, characters: names.join(","), lines: found.length },
    }),
  ];
}

/** AGF505 for instructions hidden in an HTML comment. */
function hiddenComments(source: TextSource): Diagnostic[] {
  const diagnostics: Diagnostic[] = [];

  for (const match of source.text.matchAll(HIDDEN_COMMENT)) {
    const content = match[1];
    const matched = OVERRIDE_PATTERNS.find((entry) => entry.pattern.test(content));
    if (!matched) continue;

    const line = source.startLine + source.text.slice(0, match.index ?? 0).split("\n").length - 1;

    diagnostics.push(
      diagnostic({
        code: "AGF505",
        message: `${source.kind} "${source.label}" hides an instruction inside an HTML comment`,
        explanation: [
          matched.why,
          "",
          "Markdown does not render an HTML comment, but an agent reading the raw file",
          "sees it. Anyone reviewing the rendered document would not.",
          "",
          `  ${content.trim().slice(0, 200)}`,
          "",
          CAVEAT,
        ].join("\n"),
        suggestion: "Remove the comment, or move the text into the visible document where it can be reviewed.",
        location: { file: source.file, line },
        data: { kind: source.kind, indicator: matched.id, hidden: true },
      }),
    );
  }

  return diagnostics;
}

/**
 * Blanks out HTML comments while preserving line structure.
 *
 * Text inside a comment is `hiddenComments`' finding. Letting the visible-wording
 * check see it too would report the same line twice under the same code, once
 * with the "hidden" framing that matters and once without.
 */
function withoutComments(text: string): string {
  return text.replace(HIDDEN_COMMENT, (match) => match.replace(/[^\n]/g, " "));
}

/** AGF505 for visible wording that addresses the agent's instructions. */
function overrideWording(source: TextSource): Diagnostic[] {
  const lines = withoutComments(source.text).split("\n");
  const diagnostics: Diagnostic[] = [];
  const reported = new Set<string>();

  for (let offset = 0; offset < lines.length; offset++) {
    const line = lines[offset];

    for (const entry of OVERRIDE_PATTERNS) {
      if (!entry.pattern.test(line)) continue;
      // One finding per indicator per file: a document about injection will
      // contain many examples, and forty findings for it is not useful.
      if (reported.has(entry.id)) continue;
      reported.add(entry.id);

      diagnostics.push(
        diagnostic({
          code: "AGF505",
          severity: "info",
          message: `${source.kind} "${source.label}" contains wording that addresses the agent's instructions`,
          explanation: [entry.why, "", `  ${line.trim().slice(0, 200)}`, "", CAVEAT].join("\n"),
          suggestion:
            "If this is documentation about prompt injection, no change is needed. If this file came from outside the team, review where it came from.",
          location: { file: source.file, line: source.startLine + offset },
          data: { kind: source.kind, indicator: entry.id, hidden: false },
        }),
      );
    }
  }

  return diagnostics;
}

/** Every injection indicator in a configuration's instruction text. */
export function auditInstructionText(configuration: AgentConfiguration): Diagnostic[] {
  return textSources(configuration).flatMap((source) => [
    ...invisibleCharacters(source),
    ...hiddenComments(source),
    ...overrideWording(source),
  ]);
}

/** Exposed for tests and documentation. */
export const INJECTION_INDICATORS: readonly string[] = OVERRIDE_PATTERNS.map((entry) => entry.id);
export const INVISIBLE_CHARACTER_NAMES: readonly string[] = INVISIBLE_CHARACTERS.map((entry) => entry.name);
