/// <reference types="node" />
/**
 * Manifest management for agentfile.
 *
 * The manifest (.agentfile-manifest.json) is the machine-readable record of
 * what agentfile owns, preserves, and knows about. It's the foundation for
 * clean, diff, rollback, and CI enforcement.
 */

import { createHash } from "crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join, relative } from "path";

// ─── Types ─────────────────────────────────────────────────────────────────

export type FileOwnership = "owned" | "preserved" | "unmanaged";

export interface ManifestEntry {
  /** Relative path from project root. */
  path: string;
  /** Ownership classification. */
  ownership: FileOwnership;
  /** Which agent generated this (e.g. "copilot", "claude:agent:developer"). */
  source: string;
  /** SHA-256 of content at last sync — used for drift detection. */
  hash: string;
  /** ISO timestamp of last generation. */
  generatedAt: string;
}

export interface Manifest {
  /** Schema version of the manifest itself. */
  version: 1;
  /** ISO timestamp of last sync. */
  lastSync: string;
  /** All tracked files. */
  files: ManifestEntry[];
}

// ─── Constants ─────────────────────────────────────────────────────────────

export const MANIFEST_FILE = ".agentfile-manifest.json";

// ─── Hash ──────────────────────────────────────────────────────────────────

export function hashContent(content: string): string {
  return createHash("sha256").update(content, "utf-8").digest("hex");
}

// ─── Generated-File Marker ─────────────────────────────────────────────────

const MARKER_PREFIX = "generated by agentfile";

/**
 * Returns the marker comment appropriate for the given file extension.
 * - `.md` / `.mdc` → HTML comment
 * - `.json`        → (no marker — JSON doesn't support comments)
 * - everything else → HTML comment
 */
export function generatedMarker(filePath: string): string | null {
  if (filePath.endsWith(".json")) return null;
  return `<!-- ${MARKER_PREFIX} — do not edit directly -->\n`;
}

/**
 * Returns true if the content starts with a generated-by-agentfile marker.
 */
export function hasGeneratedMarker(content: string): boolean {
  return content.trimStart().startsWith(`<!-- ${MARKER_PREFIX}`);
}

/**
 * Prepends the generated marker to content, if the file type supports it.
 * If the marker is already present, returns content unchanged.
 */
export function addMarker(filePath: string, content: string): string {
  const marker = generatedMarker(filePath);
  if (!marker) return content;
  if (hasGeneratedMarker(content)) return content;
  return marker + content;
}

// ─── Read / Write ──────────────────────────────────────────────────────────

export function readManifest(root: string): Manifest | null {
  const manifestPath = join(root, MANIFEST_FILE);
  if (!existsSync(manifestPath)) return null;
  try {
    return JSON.parse(readFileSync(manifestPath, "utf-8"));
  } catch {
    return null;
  }
}

export function writeManifest(root: string, manifest: Manifest): void {
  const manifestPath = join(root, MANIFEST_FILE);
  const dir = dirname(manifestPath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf-8");
}

// ─── Builder ───────────────────────────────────────────────────────────────

/**
 * Builds a new manifest from generation results.
 * Called by `sync` after generate() completes.
 *
 * @param root        Project root directory.
 * @param ownedFiles  Map of relative-path → { content, source }.
 *                    Written by the generator for each generated file.
 * @param previous    The previous manifest (if any), used to carry forward
 *                    preserved/unmanaged entries.
 */
export function buildManifest(
  ownedFiles: Map<string, { content: string; source: string }>,
  previous: Manifest | null,
): Manifest {
  const now = new Date().toISOString();
  const entries: ManifestEntry[] = [];

  // All freshly generated files → owned
  for (const [path, { content, source }] of ownedFiles) {
    entries.push({
      path,
      ownership: "owned",
      source,
      hash: hashContent(content),
      generatedAt: now,
    });
  }

  // Carry forward preserved/unmanaged from previous manifest
  if (previous) {
    for (const prev of previous.files) {
      if (prev.ownership !== "owned" && !ownedFiles.has(prev.path)) {
        entries.push(prev);
      }
    }
  }

  // Sort for deterministic output
  entries.sort((a, b) => a.path.localeCompare(b.path));

  return { version: 1, lastSync: now, files: entries };
}

// ─── Queries ───────────────────────────────────────────────────────────────

/** Returns all paths the manifest considers owned. */
export function ownedPaths(manifest: Manifest): string[] {
  return manifest.files.filter((f) => f.ownership === "owned").map((f) => f.path);
}

/** Returns all paths the manifest considers preserved. */
export function preservedPaths(manifest: Manifest): string[] {
  return manifest.files.filter((f) => f.ownership === "preserved").map((f) => f.path);
}

/**
 * Detects drift: files on disk whose content differs from the manifest hash.
 * Returns an array of paths that have drifted.
 */
export function detectDrift(root: string, manifest: Manifest): string[] {
  const drifted: string[] = [];
  for (const entry of manifest.files) {
    if (entry.ownership !== "owned") continue;
    const absPath = join(root, entry.path);
    if (!existsSync(absPath)) {
      drifted.push(entry.path);
      continue;
    }
    const currentHash = hashContent(readFileSync(absPath, "utf-8"));
    if (currentHash !== entry.hash) {
      drifted.push(entry.path);
    }
  }
  return drifted;
}

/**
 * Returns owned files from a previous manifest that are no longer generated.
 * These are candidates for garbage collection.
 */
export function staleFiles(previous: Manifest, current: Manifest): string[] {
  const currentOwned = new Set(ownedPaths(current));
  return ownedPaths(previous).filter((p) => !currentOwned.has(p));
}

// ─── Backup ────────────────────────────────────────────────────────────────

export const BACKUP_DIR = ".agentfile-backup";

export interface BackupEntry {
  path: string;
  content: string;
}

/**
 * Reads file contents for the given paths and returns them as backup entries.
 * Skips files that don't exist on disk.
 */
export function captureBackup(root: string, paths: string[]): BackupEntry[] {
  const entries: BackupEntry[] = [];
  for (const p of paths) {
    const absPath = join(root, p);
    if (existsSync(absPath)) {
      entries.push({ path: p, content: readFileSync(absPath, "utf-8") });
    }
  }
  return entries;
}

/**
 * Writes backup entries to the backup directory.
 */
export function writeBackup(root: string, entries: BackupEntry[], tag: string): string {
  const backupRoot = join(root, BACKUP_DIR, tag);
  for (const entry of entries) {
    const dest = join(backupRoot, entry.path);
    const dir = dirname(dest);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(dest, entry.content, "utf-8");
  }
  return backupRoot;
}

/**
 * Reads all backup entries from a given backup tag.
 */
export function readBackup(root: string, tag: string): BackupEntry[] {
  const backupRoot = join(root, BACKUP_DIR, tag);
  if (!existsSync(backupRoot)) return [];
  const entries: BackupEntry[] = [];

  function walk(dir: string): void {
    for (const dirent of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, dirent.name);
      if (dirent.isDirectory()) {
        walk(full);
      } else {
        const relPath = relative(backupRoot, full);
        entries.push({ path: relPath, content: readFileSync(full, "utf-8") });
      }
    }
  }

  walk(backupRoot);
  return entries;
}

/**
 * Restores backup entries to the project root.
 */
export function restoreBackup(root: string, entries: BackupEntry[]): string[] {
  const restored: string[] = [];
  for (const entry of entries) {
    const dest = join(root, entry.path);
    const dir = dirname(dest);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(dest, entry.content, "utf-8");
    restored.push(entry.path);
  }
  return restored;
}

/**
 * Lists available backup tags.
 */
export function listBackups(root: string): string[] {
  const backupDir = join(root, BACKUP_DIR);
  if (!existsSync(backupDir)) return [];
  return readdirSync(backupDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()
    .reverse();
}
