/// <reference types="node" />
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { compileCommand } from "../src/commands/compile.js";

const TEST_DIR = join(process.cwd(), "__test_compile__");

function cleanup() {
  if (existsSync(TEST_DIR)) rmSync(TEST_DIR, { recursive: true, force: true });
}

function write(relative: string, content: string) {
  const target = join(TEST_DIR, relative);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, content, "utf-8");
}

function read(relative: string): string {
  return readFileSync(join(TEST_DIR, relative), "utf-8");
}

function captureOutput() {
  const chunks: string[] = [];
  const log = vi.spyOn(console, "log").mockImplementation((...args: unknown[]) => {
    chunks.push(args.map(String).join(" "));
  });
  const stdout = vi.spyOn(process.stdout, "write").mockImplementation((value: unknown) => {
    chunks.push(String(value));
    return true;
  });

  return {
    text: () => chunks.join("\n"),
    restore: () => {
      log.mockRestore();
      stdout.mockRestore();
    },
  };
}

describe("compile command", () => {
  let exitSpy: ReturnType<typeof vi.spyOn>;
  let exitCodes: number[];

  beforeEach(() => {
    cleanup();
    mkdirSync(TEST_DIR, { recursive: true });
    exitCodes = [];
    exitSpy = vi.spyOn(process, "exit").mockImplementation(((code?: number) => {
      exitCodes.push(code ?? 0);
      return undefined as never;
    }) as never);
  });

  afterEach(() => {
    exitSpy.mockRestore();
    vi.restoreAllMocks();
    cleanup();
  });

  it("requires explicit targets rather than guessing", async () => {
    const output = captureOutput();
    await compileCommand({ root: TEST_DIR });
    const text = output.text();
    output.restore();

    expect(text).toContain("--target");
    expect(exitCodes).toContain(2);
  });

  it("points codex at agents-md instead of pretending to support it", async () => {
    const output = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["codex"] });
    const text = output.text();
    output.restore();

    expect(text).toContain("agents-md");
    expect(exitCodes).toContain(2);
  });

  it("compiles AGENTS.md into a marked CLAUDE.md and records it in the manifest", async () => {
    write("AGENTS.md", "Use pnpm, never npm.\n");

    const output = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["claude"] });
    output.restore();

    expect(exitCodes).toEqual([]);
    const compiled = read("CLAUDE.md");
    expect(compiled).toMatch(/^<!-- generated by agentfile/);
    expect(compiled).toContain("Use pnpm, never npm.");

    const manifest = JSON.parse(read(".agentfile-manifest.json"));
    expect(manifest.files.some((entry: { path: string }) => entry.path === "CLAUDE.md")).toBe(true);
  });

  it("is idempotent: a second run reports everything up to date", async () => {
    write("AGENTS.md", "Use pnpm.\n");

    const first = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["claude"] });
    first.restore();
    const compiled = read("CLAUDE.md");

    const second = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["claude"] });
    const text = second.text();
    second.restore();

    expect(read("CLAUDE.md")).toBe(compiled);
    expect(text).toContain("up to date");
    expect(exitCodes).toEqual([]);
  });

  it("check mode reports drift with exit 1 and writes nothing", async () => {
    write("AGENTS.md", "Use pnpm.\n");

    const output = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["claude"], check: true });
    const text = output.text();
    output.restore();

    expect(text).toContain("out of date");
    expect(exitCodes).toEqual([1]);
    expect(existsSync(join(TEST_DIR, "CLAUDE.md"))).toBe(false);
  });

  it("check mode exits 0 when the output is current", async () => {
    write("AGENTS.md", "Use pnpm.\n");

    const compile = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["claude"] });
    compile.restore();

    const check = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["claude"], check: true });
    const text = check.text();
    check.restore();

    expect(text).toContain("up to date");
    expect(exitCodes).toEqual([]);
  });

  it("refuses to overwrite a hand-written file and says how to proceed", async () => {
    write("AGENTS.md", "Use pnpm.\n");
    write("CLAUDE.md", "# Hand-written memory file\n");

    const output = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["claude"] });
    const text = output.text();
    output.restore();

    expect(text).toContain("AGF204");
    expect(read("CLAUDE.md")).toBe("# Hand-written memory file\n");
    expect(exitCodes).toEqual([1]);

    exitCodes.length = 0;
    const forced = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["claude"], force: true });
    forced.restore();

    expect(read("CLAUDE.md")).toContain("Use pnpm.");
    expect(exitCodes).toEqual([]);
  });

  it("reports fidelity losses for a target that cannot express a scope", async () => {
    write(
      ".claude/rules/api.md",
      ["---", 'paths:', '  - "src/api/**"', "---", "API rules.", ""].join("\n"),
    );
    write("CLAUDE.md", "Root rules.\n");

    const output = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["agents-md"] });
    const text = output.text();
    output.restore();

    expect(text).toContain("AGF201");
    expect(read("AGENTS.md")).toContain("Root rules.");
  });

  it("does not compile a generated file back into another target", async () => {
    write("AGENTS.md", "Use pnpm.\n");

    const toClaude = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["claude"] });
    toClaude.restore();

    // The generated CLAUDE.md must not double the content when compiling
    // the cursor target from the same tree.
    const toCursor = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["cursor"] });
    toCursor.restore();

    const rule = read(".cursor/rules/agentfile.mdc");
    expect(rule.match(/Use pnpm/g)).toHaveLength(1);
  });

  it("emits a machine-readable plan", async () => {
    write("AGENTS.md", "Use pnpm.\n");

    const output = captureOutput();
    await compileCommand({ root: TEST_DIR, target: ["claude", "cursor"], format: "json" });
    const text = output.text();
    output.restore();

    const report = JSON.parse(text);
    expect(report.command).toBe("compile");
    expect(report.files.map((file: { path: string }) => file.path)).toEqual([
      ".cursor/rules/agentfile.mdc",
      "CLAUDE.md",
    ]);
    expect(report.written).toHaveLength(2);
    expect(exitCodes).toEqual([]);
  });
});
